### ISSUE TITLE
Module installation failed

### ISSUE THREAD

**Issue by gb0k** [WordlessEcho/Source-Han-VF-Magisk#3]
Failed to install the latest Source Han VF Magisk module.
Told me file corrupted
![Screenshot_20210413-105450](https://user-images.githubusercontent.com/30920372/114496972-a89cd080-9c53-11eb-80aa-424750d675a6.jpg)
Device is op7 pro
On latest oos11

**Comment by WordlessEcho** [comment]
Thanks for your feedback! Please try latest release.
